// client/src/components/TimerCountdown.vue
<template>
    <div>
        &nbsp;{{ getRemainingTime() }}&nbsp;
    </div>
</template>

<script lang="ts">

import {defineComponent} from "vue";

export default defineComponent({
    props: {
        endTimestamp: Date
    },
    data() {
        return {
            name: "TimerCountdown",
            days: 0,
            hours: 0,
            minutes: 0,
            seconds: 0,
        }
    },
    computed: {
        _seconds: () => 1000,
        _minutes() {
            return this._seconds * 60
        },
        _hours() {
            return this._minutes * 60
        },
        _days() {
            return this._hours * 24
        }
    },
    methods: {
        formatNumber: function (num: number) : string {
            return num < 10 ? "0" + num.toString(10) : num.toString(10);
        },
        calcRemainingTime: function () {
            const timer = setInterval(() => {
                const now = new Date();
                const end = new Date(this.endTimestamp);
                const time = end.getTime() - now.getTime();
                if (time < 0) {
                    clearInterval(timer)
                    return;
                }
                const days = Math.floor(time / this._days);
                const hours = Math.floor((time % this._days) / this._hours);
                const minutes = Math.floor((time % this._hours) / this._minutes);
                const seconds = Math.floor((time % this._minutes) / this._seconds);
                this.days = this.formatNumber(days);
                this.hours = this.formatNumber(hours);
                this.minutes = this.formatNumber(minutes);
                this.seconds = this.formatNumber(seconds);
            }, 1000)
        },
        getRemainingTime: function () {
            return (this.days !== 0 && this.hours !== 0 && this.minutes !== 0 && this.seconds !== 0) ?
                `${this.days}:${this.hours}:${this.minutes}:${this.seconds}` :
                "OVER!";
        }
    },
    mounted() {
        this.calcRemainingTime()
    }
});
</script>

<style scoped>
</style>

// client/src/components/Shared/TimerCountdown/index.tsx
import * as React from "react";

interface Props {
  endTimestamp: number;
}

const TimerCountdown = ({ endTimestamp }: Props): React.ReactElement => {
  const [time, setTime] = React.useState({
    days: "",
    hours: "",
    minutes: "",
    seconds: "",
  });

  const _seconds = () => 1000;

  const _minutes = () => {
    return _seconds() * 60;
  };
  const _hours = () => {
    return _minutes() * 60;
  };
  const _days = () => {
    return _hours() * 24;
  };

  const formatNumber = (num: number): string => {
    return num < 10 ? "0" + num.toString(10) : num.toString(10);
  };

  const calcRemainingTime = () => {
    const timer = setInterval(() => {
      const now = new Date();
      const end = new Date(endTimestamp);

      const totalTime = now.getTime() - end.getTime();
      if (totalTime < 0) {
        clearInterval(timer);
        return;
      }

      const days = Math.floor(totalTime / _days());
      const hours = Math.floor((totalTime % _days()) / _hours());
      const minutes = Math.floor((totalTime % _hours()) / _minutes());
      const seconds = Math.floor((totalTime % _minutes()) / _seconds());
      time.days = formatNumber(days);
      time.hours = formatNumber(hours);
      time.minutes = formatNumber(minutes);
      time.seconds = formatNumber(seconds);
      setTime({ ...time });
      
    }, 1000);
  };

  const getRemainingTime = (): string => {
    return time.days !== "0" &&
      time.hours !== "0" &&
      time.minutes !== "0" &&
      time.seconds !== "0"
      ? `${time.days}:${time.hours}:${time.minutes}:${time.seconds}`
      : "OVER!";
  };

  calcRemainingTime();

  return <> {getRemainingTime()} </>;
};

export default TimerCountdown;
