// client/src/components/user/AttendanceList.vue
<template>
    <br/>
    <h2>
        <label for="contestName">Select contest: </label>
        <select id="contestName">
            <option v-for="contest in contests" :key="contest" @click="selectContest(contest)">
                {{ contest.name }}
            </option>
        </select>
    </h2>
    <div v-if="selected !== null">
        <v-text-field v-model="searchQuery" class="search" label="University ID"/>
        <div v-if="users.length > 0">
            <div class="grid" v-for="user in filterUsers()" :key="user">
                <div class="bg-purple-accent-4 card">
                    <UserCard :user="user"/>
                    <v-btn @click="checkAttended(user)">Attended</v-btn>
                </div>
            </div>
        </div>
        <h1 class="text-red">no users were found!</h1>
    </div>
</template>

<script lang="ts">
import {defineComponent} from "vue";
import OrganizerRequests from "@/utils/requests/OrganizerRequests";
import Contest from "@/models/Contest";
import UserCard from "@/components/user/UserCard.vue";
import User from "@/models/User";

export default defineComponent({
    name: "AttendanceList",
    components: {UserCard},
    data() {
        return {
            searchQuery: "",
            users: [],
            contests: [],
            selected: null
        }
    },
    async mounted() {
        this.contests = await OrganizerRequests.getContests();
        this.selected = this.contests[0];
        this.users = await OrganizerRequests.getParticipantsList(this.selected);
    },
    methods: {
        filterUsers(): User[] {
            return this.users
                .filter((user: User) => user.email?.includes(this.searchQuery))
                .slice(0, this.users.length >= 10 ? 10 : this.users.length);
        },
        async checkAttended(user: User) {
            await OrganizerRequests.markParticipantAsPresent(user, this.selected);
            this.users.splice(this.users.indexOf(user), 1);
        },
        selectContest(contest: Contest) {
            this.selected = contest;
        }
    }
});
</script>

<style scoped>
.grid {
    display: inline-grid;
    padding: 20px;
}

.card {
    border-radius: 5px;
    padding: 10px;
}

.search {
    margin: 0 auto;
    width: 500px;
}
</style>

// client/src/components/Organizer/AttendanceList/index.tsx
import { Button, TextField } from "@mui/material";
import * as React from "react";
import { BiUser } from "react-icons/bi";
import { MdDone } from "react-icons/md";
import Contest from "../../../models/Contest";
import User from "../../../models/User";
import OrganizerRequests from "../../../utils/requests/OrganizerRequests";

interface Props {
  contest: Contest;
}

const AttentanceList = ({ contest }: Props): React.ReactElement => {
  const [participants, setParticipants] = React.useState(new Array<User>());

  React.useEffect(() => {
    (async () => {
      setParticipants(await OrganizerRequests.getParticipantsList(contest));
    })();
  }, [contest]);

  const [searchQuery, setSearchQuery] = React.useState("");

  const filterUsers = (): User[] => {
    return participants.filter((user) => user.email?.includes(searchQuery));
    // .slice(0, participants.length >= 10? 10: participants.length);
  };

  const checkAttended = (user: User) => {
    (async () => {
      await OrganizerRequests.markParticipantAsPresent(user, contest);
      setParticipants(
        participants.splice(
          participants.findIndex((u) => u.email === user.email),
          1
        )
      );
    })();
  };

  return (
    <>
      {participants !== null && participants.length === 0 && (
        <>
          <div className="pb-[20px] px-[14px]">
            <TextField
              className="w-[100%]"
              variant="outlined"
              value={searchQuery}
              onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                setSearchQuery(event.target.value);
              }}
              label={
                <label className="font-Ropa text-[18px] text-indigo">
                  University ID (email)
                </label>
              }
            />
          </div>
          <div className="grid w-full grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">
            {filterUsers().map((user) => (
              <>
                <div
                  key={user.id}
                  className="float-left border-[1px] border-indigo rounded h-auto inline-block w-[280px] ml-[16px] mb-[16px] last:mb-0 font-Ropa p-[25px]"
                >
                  <BiUser className="inline" />
                  <label>&nbsp;{user.name}</label>
                  <hr className="pb-[10px] mt-[10px]" />
                  <label>{user.email}</label>
                  <hr className="pb-[10px] mt-[10px]" />
                  <Button
                    endIcon={<MdDone size={12} />}
                    color="info"
                    variant="outlined"
                    size="large"
                    onClick={() => checkAttended(user)}
                  >
                    <label className="normal-case font-Ropa cursor-pointer">
                      Attended
                    </label>
                  </Button>
                </div>
              </>
            ))}
          </div>{" "}
          {/*}*/}
        </>
      )}
    </>
  );
};

export default AttentanceList;
